name: Deploy to prod

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull master and restart gunicorn
        run: bash ${GITHUB_WORKSPACE}/scripts/deploy.sh "$DEPLOY_KEY"
