name: Deploy to prod

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull master and restart gunicorn
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: bash .github/scripts/deploy.sh
